# Generated by Django 2.1.2 on 2020-04-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_api', '0013_auto_20190525_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ft_resultadoByAno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_incidencias', models.IntegerField(default=0)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_ano_id_ano', to='plataforma_api.Dim_ano')),
            ],
        ),
    ]
